### ISSUE TITLE
Outdated plugin

### ISSUE THREAD

**Issue by EpicCatto** [storefront-bvba/btcpayserver-plugin-autoforward#1]
Auto-Forward Plugin is unable to load on the newer version of the btcpayserver.

**Comment by islandbitcoin** [comment]
+1

**Comment by nyxmr** [comment]
+1

**Comment by dme1sc** [comment]
If this is the error - then I +1...

Npgsql.PostgresException (0x80004005): 42703: column b.xmin does not exist
POSITION: 160
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at BTCPayServer.Plugins.AutoForward.Services.AutoForwardInvoiceHelper.GetInvoicesBySql(String sql) in /build/BTCPayServer.Plugins.AutoForward/Services/AutoForwardInvoiceHelper.cs:line 93
   at BTCPayServer.Plugins.AutoForward.Services.AutoForwardInvoiceHelper.GetAutoForwardableInvoicesNotPaidOut() in /build/BTCPayServer.Plugins.AutoForward/Services/AutoForwardInvoiceHelper.cs:line 71
   at BTCPayServer.Plugins.AutoForward.Services.AutoForwardInvoiceHelper.UpdateEverything(CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.AutoForward/Services/AutoForwardInvoiceHelper.cs:line 562
   at BTCPayServer.Plugins.AutoForward.Services.BlockWatcher.ProcessEvent(Object evt, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.AutoForward/Services/BlockWatcher.cs:line 44
  Exception data:
    Severity: ERROR
    SqlState: 42703
    MessageText: column b.xmin does not exist
    Position: 160
    File: parse_relation.c
    Line: 3553
    Routine: errorMissingColumn

Level
Fatal
Timestamp
9/14/2024 10:23:51 PM +00:00

SourceContext
"AutoForward"

**Comment by Caredas** [comment]
Same problem with version © BTCPay Server v1.13.5+30d91d0bd (Altcoins)
